# -*- coding: utf-8 -*-
"""Targil5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17CqBWnrFZHAjfOCvBdD3QsRtnvsIj6R4

# Ranit Zohar , 
#Aviah Miriam Yadler 

תרגיל 5

שאלה 1

סעיף א
"""

import time

Linearit=lambda x: x/2+2
print(Linearit(2))

"""יצירת מערך בפונקציית על"""

L2=list(range(10001))
print(L2)
L3=list(map( Linearit,L2))
print(L3)

"""סעיף ב

סכום מערך בפונקציית על
"""

tic = time.time()
sum1=sum(map(lambda x : x, L2))
print(sum1)
toc = time.time()
(toc-tic)*1000

"""סכום מערך בצורה אימפרטיבית"""

tic = time.time()
i=1
sum1=0
while i<=10000:
    sum1=sum1+L2[i]
    i+=1
print(sum1)
toc = time.time()
(toc-tic)*1000

"""סעיף ג: זמן הריצה בפונקציית על יצא יותר מהר- 2.21
לעומת הצורה האימפרטיבית שיצא- 3.26

סעיף ד
"""

sum(list(map(lambda x: x/2+2,L2)))

"""שאלה 2"""

L1=list(range(1,10001))

LZogi=[item for item in L1 if item%2==0]
LNotZogi=[item for item in L1 if item%2==1]
print(LZogi)
print(LNotZogi)

"""סעיף א"""

from functools import reduce

"""עבור זוגי"""

def funZ(L):
  return reduce(lambda x,y: x*y , L)

"""עבור אי זוגי"""

def funNZ(L):
  return reduce(lambda x,next: x/2+2+next , L)

"""סעיף ב+ג,
בהתאם למה שחיה אמרה
"""

zogi= funZ(LZogi)
print(zogi)

NotZ= funNZ(LNotZogi)
print(NotZ)

"""שאלה 3"""

def add1(a):
  return a+1

Leee=range(1,10)

"""זאת הפונקציה המבוקשת בשאלה 3"""

def printHigh (L,func):
  result=[func(item) for item in L]
  print(result)

aa=printHigh(Leee,add1)

"""שאר הדברים זה בדיקה שהפונקציה עובדת כראוי

שאלה 4

סעיף א- קוד המחזיר פונקציה
"""

def func4(num):
  return lambda x: pow(x,num)

pwr4 = func4(4)

type(pwr4)

pwr4(2)

"""סעיף ב-	בעזרת שימוש בספריה
 functool
"""

from functools import partial

def power(base, exponent):
    return pow(base, exponent)

power4 = partial(power, 4)
print(power4(2))

"""בדיקה """

print(power(2, 4))